/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.Timer;
import model.Dragon;
import model.Jugador;

/**
 *
 * @author Victus
 */
public class MainView extends javax.swing.JFrame {

    private List<Dragon> dragonesTierra;
    private List<Dragon> dragonesFuego;
    private Jugador jugador; 
    
    DefaultListModel modelo = new DefaultListModel();
    
    public MainView(List<Dragon> dragonesTierra, List<Dragon> dragonesFuego) {
        initComponents();
        initJugador();
        initBarraExp();
        
        jList1.setModel(modelo);
        
        this.dragonesTierra = dragonesTierra;
        this.dragonesFuego = dragonesFuego;
        
        DragonesT.setVisible(false);
        AplicarT.setVisible(false);
        DragonTierra1.setVisible(false);
        DragonTierra2.setVisible(false);
        DragonFuego1.setVisible(false);
        DragonFuego2.setVisible(false);
        jScrollPane1.setVisible(false);
        jList1.setVisible(false);
        DragonesF.setVisible(false);
        AplicarF.setVisible(false);
    }

    private MainView() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pantalla = new javax.swing.JPanel();
        DragonTierra1 = new javax.swing.JLabel();
        DragonTierra2 = new javax.swing.JLabel();
        MejoraHabitatT = new javax.swing.JButton();
        HabitatTierra = new javax.swing.JButton();
        DragonesT = new javax.swing.JComboBox<>();
        AplicarT = new javax.swing.JButton();
        DragonesF = new javax.swing.JComboBox<>();
        AplicarF = new javax.swing.JButton();
        DragonFuego1 = new javax.swing.JLabel();
        DragonFuego2 = new javax.swing.JLabel();
        MejoraHabitatF = new javax.swing.JButton();
        HabitatFuego = new javax.swing.JButton();
        Jugador = new javax.swing.JButton();
        BarraNivel = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Pantalla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(1123, 0, -1, -1));

        DragonTierra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dragones/Dragon tierra bebe.png"))); // NOI18N
        getContentPane().add(DragonTierra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        DragonTierra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dragones/Bebe-dragon-barro.png"))); // NOI18N
        getContentPane().add(DragonTierra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, -1));

        MejoraHabitatT.setBackground(new java.awt.Color(0, 153, 51));
        MejoraHabitatT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/utilidades/mejora.png"))); // NOI18N
        getContentPane().add(MejoraHabitatT, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 30, 30));

        HabitatTierra.setBackground(new java.awt.Color(0, 153, 51));
        HabitatTierra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/utilidades/habitat_arena.png"))); // NOI18N
        HabitatTierra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HabitatTierraActionPerformed(evt);
            }
        });
        getContentPane().add(HabitatTierra, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 100, 90));

        getContentPane().add(DragonesT, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 100, -1));

        AplicarT.setText("Aplicar");
        AplicarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AplicarTActionPerformed(evt);
            }
        });
        getContentPane().add(AplicarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, 20));

        DragonesF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        getContentPane().add(DragonesF, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 100, -1));

        AplicarF.setText("Aplicar");
        AplicarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AplicarFActionPerformed(evt);
            }
        });
        getContentPane().add(AplicarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, -1, -1));

        DragonFuego1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dragones/Dragon_fuego.png"))); // NOI18N
        getContentPane().add(DragonFuego1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, -1, -1));

        DragonFuego2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dragones/Flaming_Rock_Dragon.png"))); // NOI18N
        getContentPane().add(DragonFuego2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 30, -1));

        MejoraHabitatF.setBackground(new java.awt.Color(0, 153, 51));
        MejoraHabitatF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/utilidades/mejora.png"))); // NOI18N
        getContentPane().add(MejoraHabitatF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 30, 30));

        HabitatFuego.setBackground(new java.awt.Color(0, 153, 51));
        HabitatFuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/utilidades/habitat_fuego.png"))); // NOI18N
        HabitatFuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HabitatFuegoActionPerformed(evt);
            }
        });
        getContentPane().add(HabitatFuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 110, 70));

        Jugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/utilidades/estrella_dc.png"))); // NOI18N
        Jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugadorActionPerformed(evt);
            }
        });
        getContentPane().add(Jugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 70, 70));
        getContentPane().add(BarraNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 70, 20));

        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 130, 80));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/utilidades/fondo.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 492));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initJugador(){
        
        jugador = new Jugador("Player 2", 1, 0, 10000, 5000);
    }
    
    private void initBarraExp(){
        
        BarraNivel.setMaximum(100);
    }
    
    private void llenarComboBoxConDragonesT(List<Dragon> dragonesTierra) {
        DragonesT.removeAllItems(); // Limpiar el JComboBox

        for (Dragon dragon : dragonesTierra) {
                DragonesT.addItem(dragon.getNombre());
        }
    }
    
    private void llenarComboBoxConDragonesF(List<Dragon> dragonesFuego) {
        DragonesF.removeAllItems(); // Limpiar el JComboBox

        for (Dragon dragon : dragonesFuego) {
                DragonesF.addItem(dragon.getNombre());
        }
    }
    
    private void mostrarInfoJugador() {
        // Actualizar la información en el modelo de la lista
        modelo.clear();
        modelo.addElement("Nombre: " + jugador.getNombre());
        modelo.addElement("Nivel: " + jugador.getNivel());
        modelo.addElement("Oro: " + jugador.getOro());
        modelo.addElement("Comida: " + jugador.getComida());

        // Mostrar la lista
        jScrollPane1.setVisible(true);

        // Crear un temporizador para ocultar la lista después de 5 segundos
        Timer timer = new Timer(5000, evt -> jScrollPane1.setVisible(false));
        timer.setRepeats(false); // Solo ejecuta una vez
        timer.start();
}
    
    private void JugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugadorActionPerformed
        jScrollPane1.setVisible(true);
        jList1.setVisible(true);
        mostrarInfoJugador();
    }//GEN-LAST:event_JugadorActionPerformed

    private void HabitatTierraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HabitatTierraActionPerformed
        llenarComboBoxConDragonesT(dragonesTierra);
        DragonesT.setVisible(true);
        AplicarT.setVisible(true);
        
        Timer timer = new Timer(5000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                DragonesT.setVisible(false);
                AplicarT.setVisible(false); 
            }
        }
        );
        
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_HabitatTierraActionPerformed

    private void HabitatFuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HabitatFuegoActionPerformed
        llenarComboBoxConDragonesF(dragonesFuego);
        DragonesF.setVisible(true);
        AplicarF.setVisible(true);
        
        Timer timer = new Timer(5000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                DragonesF.setVisible(false);
                AplicarF.setVisible(false); 
            }
        }
        );
        
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_HabitatFuegoActionPerformed

    private void AplicarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AplicarTActionPerformed
        String dragon = DragonesT.getSelectedItem().toString();
        System.out.println("Dragon: " + dragon);
        
        if("Dave".equals(dragon)){
            
            DragonTierra1.setVisible(true);
            DragonTierra2.setVisible(false);
            
        }else if("Steve".equals(dragon)){
            
            DragonTierra1.setVisible(false);
            DragonTierra2.setVisible(true);
        }
    }//GEN-LAST:event_AplicarTActionPerformed

    private void AplicarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AplicarFActionPerformed
        String dragon = DragonesF.getSelectedItem().toString();
        System.out.println("Dragon: " + dragon);
        
        if("Loche".equals(dragon)){
            DragonFuego1.setVisible(true);
            DragonFuego2.setVisible(false);
        }else if("Bitz".equals(dragon)){
            DragonFuego1.setVisible(false);
            DragonFuego2.setVisible(true);
        }
    }//GEN-LAST:event_AplicarFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AplicarF;
    private javax.swing.JButton AplicarT;
    private javax.swing.JProgressBar BarraNivel;
    private javax.swing.JLabel DragonFuego1;
    private javax.swing.JLabel DragonFuego2;
    private javax.swing.JLabel DragonTierra1;
    private javax.swing.JLabel DragonTierra2;
    private javax.swing.JComboBox<String> DragonesF;
    private javax.swing.JComboBox<String> DragonesT;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton HabitatFuego;
    private javax.swing.JButton HabitatTierra;
    private javax.swing.JButton Jugador;
    private javax.swing.JButton MejoraHabitatF;
    private javax.swing.JButton MejoraHabitatT;
    private javax.swing.JPanel Pantalla;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
