/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.Timer;
import model.Dragon;
import model.Habitat;
import model.Jugador;
import model.TipoDragon;

/**
 *
 * @author Victus
 */
public class MainView extends javax.swing.JFrame {

    private List<Dragon> dragonesTierra;
    private List<Dragon> dragonesFuego;
    private Jugador jugador; 
    private Thread experiencia;
    
    ArrayList infoJugador = new ArrayList();
    DefaultListModel modelo = new DefaultListModel();
    
    public MainView(List<Dragon> dragonesTierra, List<Dragon> dragonesFuego) {
        initComponents();
        initJugador();
        initBarraExp();
        
        jList1.setModel(modelo);
        
        this.dragonesTierra = dragonesTierra;
        this.dragonesFuego = dragonesFuego;
        
        DragonesT.setVisible(false);
        AplicarT.setVisible(false);
        DragonTierra1.setVisible(false);
        DragonTierra2.setVisible(false);
        DragonFuego1.setVisible(false);
        DragonFuego2.setVisible(false);
        jScrollPane2.setVisible(false);
        jList1.setVisible(false);
        DragonesF.setVisible(false);
        AplicarF.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pantalla = new javax.swing.JPanel();
        DragonesT = new javax.swing.JComboBox<>();
        AplicarT = new javax.swing.JButton();
        DragonTierra1 = new javax.swing.JLabel();
        DragonTierra2 = new javax.swing.JLabel();
        MejoraHabitatT = new javax.swing.JButton();
        HabitatTierra = new javax.swing.JButton();
        DragonesF = new javax.swing.JComboBox<>();
        AplicarF = new javax.swing.JButton();
        DragonFuego1 = new javax.swing.JLabel();
        DragonFuego2 = new javax.swing.JLabel();
        MejoraHabitatF = new javax.swing.JButton();
        HabitatFuego = new javax.swing.JButton();
        Jugador = new javax.swing.JButton();
        BarraNivel = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pantalla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Pantalla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DragonesT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DragonesT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Steve", "Dave", " " }));
        DragonesT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DragonesTActionPerformed(evt);
            }
        });
        Pantalla.add(DragonesT, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 100, -1));

        AplicarT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AplicarT.setText("Aplicar");
        AplicarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AplicarTActionPerformed(evt);
            }
        });
        Pantalla.add(AplicarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, 20));

        DragonTierra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dragones/Dragon tierra bebe.png"))); // NOI18N
        Pantalla.add(DragonTierra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 30, 30));

        DragonTierra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dragones/Bebe-dragon-barro.png"))); // NOI18N
        Pantalla.add(DragonTierra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 30, 30));

        MejoraHabitatT.setBackground(new java.awt.Color(0, 153, 51));
        MejoraHabitatT.setForeground(new java.awt.Color(0, 204, 0));
        MejoraHabitatT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/utilidades/mejora.png"))); // NOI18N
        MejoraHabitatT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MejoraHabitatTActionPerformed(evt);
            }
        });
        Pantalla.add(MejoraHabitatT, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 30, 30));

        HabitatTierra.setBackground(new java.awt.Color(0, 153, 51));
        HabitatTierra.setForeground(new java.awt.Color(0, 153, 51));
        HabitatTierra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/utilidades/habitat_arena.png"))); // NOI18N
        HabitatTierra.setText("BotonDragon");
        HabitatTierra.setToolTipText("");
        HabitatTierra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HabitatTierraActionPerformed(evt);
            }
        });
        Pantalla.add(HabitatTierra, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 100, 80));

        DragonesF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DragonesF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loche", " " }));
        DragonesF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DragonesFActionPerformed(evt);
            }
        });
        Pantalla.add(DragonesF, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, 100, 20));

        AplicarF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        AplicarF.setText("Aplicar");
        AplicarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AplicarFActionPerformed(evt);
            }
        });
        Pantalla.add(AplicarF, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, 20));

        DragonFuego1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dragones/Dragon_fuego.png"))); // NOI18N
        Pantalla.add(DragonFuego1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 30, 30));

        DragonFuego2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dragones/Flaming_Rock_Dragon.png"))); // NOI18N
        Pantalla.add(DragonFuego2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 30, 30));

        MejoraHabitatF.setBackground(new java.awt.Color(0, 153, 51));
        MejoraHabitatF.setForeground(new java.awt.Color(0, 204, 0));
        MejoraHabitatF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/utilidades/mejora.png"))); // NOI18N
        MejoraHabitatF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MejoraHabitatFActionPerformed(evt);
            }
        });
        Pantalla.add(MejoraHabitatF, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 30, 30));

        HabitatFuego.setBackground(new java.awt.Color(0, 153, 51));
        HabitatFuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/utilidades/habitat_fuego.png"))); // NOI18N
        HabitatFuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HabitatFuegoActionPerformed(evt);
            }
        });
        Pantalla.add(HabitatFuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 100, 70));

        Jugador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/utilidades/estrella_dc.png"))); // NOI18N
        Jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugadorActionPerformed(evt);
            }
        });
        Pantalla.add(Jugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 70, 70));

        BarraNivel.setForeground(new java.awt.Color(0, 204, 255));
        Pantalla.add(BarraNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 70, 20));

        jList1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(jList1);

        Pantalla.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 130, 80));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/utilidades/fondo.png"))); // NOI18N
        Pantalla.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void initJugador(){
        
        jugador = new Jugador("Player 2", 1, 0, 10000, 5000);
    }
    
    private void initBarraExp(){
        
        BarraNivel.setMaximum(100);
    }
    
    private void llenarComboBoxConDragonesT(List<Dragon> dragonesTierra) {
        DragonesT.removeAllItems(); // Limpiar el JComboBox

        for (Dragon dragon : dragonesTierra) {
                DragonesT.addItem(dragon.getNombre());
        }
    }
    
    private void llenarComboBoxConDragonesF(List<Dragon> dragonesFuego) {
        DragonesF.removeAllItems(); // Limpiar el JComboBox

        for (Dragon dragon : dragonesFuego) {
                DragonesF.addItem(dragon.getNombre());
        }
    }
    
    private void mostrarInfoJugador() {
        // Actualizar la información en el modelo de la lista
        modelo.clear();
        modelo.addElement("Nombre: " + jugador.getNombre());
        modelo.addElement("Nivel: " + jugador.getNivel());
        modelo.addElement("Oro: " + jugador.getOro());
        modelo.addElement("Comida: " + jugador.getComida());

        // Mostrar la lista
        jScrollPane2.setVisible(true);

        // Crear un temporizador para ocultar la lista después de 5 segundos
        Timer timer = new Timer(5000, evt -> jScrollPane2.setVisible(false));
        timer.setRepeats(false); // Solo ejecuta una vez
        timer.start();
}
    
    private void HabitatTierraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HabitatTierraActionPerformed
        llenarComboBoxConDragonesT(dragonesTierra);
        DragonesT.setVisible(true);
        AplicarT.setVisible(true);
        
        Timer timer = new Timer(5000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                DragonesT.setVisible(false);
                AplicarT.setVisible(false); 
            }
        }
        );
        
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_HabitatTierraActionPerformed

    private void DragonesTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DragonesTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DragonesTActionPerformed

    private void AplicarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AplicarTActionPerformed
        String dragon = DragonesT.getSelectedItem().toString();
        System.out.println("Dragon: " + dragon);
        
        if("Dave".equals(dragon)){
            
            DragonTierra1.setVisible(true);
            DragonTierra2.setVisible(false);
            
        }else if("Steve".equals(dragon)){
            
            DragonTierra1.setVisible(false);
            DragonTierra2.setVisible(true);
        }
        
    }//GEN-LAST:event_AplicarTActionPerformed

    private void JugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugadorActionPerformed
        jScrollPane2.setVisible(true);
        jList1.setVisible(true);
        mostrarInfoJugador();
    }//GEN-LAST:event_JugadorActionPerformed

    private void MejoraHabitatTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MejoraHabitatTActionPerformed
        // TODO add your handling code here:     
    }//GEN-LAST:event_MejoraHabitatTActionPerformed

    private void MejoraHabitatFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MejoraHabitatFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MejoraHabitatFActionPerformed

    private void DragonesFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DragonesFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DragonesFActionPerformed

    private void AplicarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AplicarFActionPerformed
        String dragon = DragonesF.getSelectedItem().toString();
        System.out.println("Dragon: " + dragon);
        
        if("Loche".equals(dragon)){
            DragonFuego1.setVisible(true);
            DragonFuego2.setVisible(false);
        }else if("Bitz".equals(dragon)){
            DragonFuego1.setVisible(false);
            DragonFuego2.setVisible(true);
        }
    }//GEN-LAST:event_AplicarFActionPerformed

    private void HabitatFuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HabitatFuegoActionPerformed
        llenarComboBoxConDragonesF(dragonesFuego);
        DragonesF.setVisible(true);
        AplicarF.setVisible(true);
        
        Timer timer = new Timer(5000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                DragonesF.setVisible(false);
                AplicarF.setVisible(false); 
            }
        }
        );
        
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_HabitatFuegoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AplicarF;
    private javax.swing.JButton AplicarT;
    private javax.swing.JProgressBar BarraNivel;
    private javax.swing.JLabel DragonFuego1;
    private javax.swing.JLabel DragonFuego2;
    private javax.swing.JLabel DragonTierra1;
    private javax.swing.JLabel DragonTierra2;
    private javax.swing.JComboBox<String> DragonesF;
    private javax.swing.JComboBox<String> DragonesT;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton HabitatFuego;
    private javax.swing.JButton HabitatTierra;
    private javax.swing.JButton Jugador;
    private javax.swing.JButton MejoraHabitatF;
    private javax.swing.JButton MejoraHabitatT;
    private javax.swing.JPanel Pantalla;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
